feat/reward donator page
DrowningToast/BloodPrompt pull request #13
Opened 2023-09-26 19:27 UTC by misterfocusth

- Created reward home page (donator) /reward
- Created reward history page (donator) /reward/history

FYI: Tomorrow I will make another page that related to rewards (/reward/history/:id) for viewing specific reward history info you can hold this pr and merge it into main when another page is ready.

2023-09-27 07:04 UTC, DrowningToast requested changes

2023-09-27 07:04 UTC, DrowningToast commented on src/app.html
>  		<link rel="icon" href="%sveltekit.assets%/favicon.png" />
import the font in the global css file instead of root HTML file

2023-09-27 07:04 UTC, DrowningToast commented on src/routes/(donator)/reward/+page.svelte
> +					window.history.back();
ใช้ goto() ของ svelte ได้ไหม

2023-09-27 07:04 UTC, DrowningToast commented on src/routes/(donator)/reward/history/+page.svelte
> +					window.history.back();
ใช้ goto() ของ svelte ได้ไหม

2023-09-27 07:04 UTC, DrowningToast commented on src/routes/login/+page.svelte
> +		<a href="/home">
ทำไมโค้ดบางไฟล์ถึงเขียน href ข้างใน Button

2023-09-27 11:23 UTC, misterfocusth commented
@DrowningToast all finish now you can review this pr and merge it.

2023-09-27 11:28 UTC, misterfocusth commented
@DrowningToast there is one page left for this branch don't merge yet.

2023-09-27 12:54 UTC, misterfocusth commented
@DrowningToast review plz.

2023-09-28 06:12 UTC, DrowningToast approved these changes
LGTM!

2023-09-28 06:12 UTC, merged